### ISSUE TITLE
Missing require() pattern

### ISSUE THREAD

**Issue by insin** [ericclemmons/npm-install-loader#11]
The parser doesn't currently pick up this pattern of `require()` usage:

```js
require('es6-promise').polyfill()
```

This looks... fiddly in [AST Explorer](http://astexplorer.net/):

![npm-install-loader-missing](https://cloud.githubusercontent.com/assets/226692/12182267/0766349c-b57f-11e5-9f44-b8d0541f601e.png)

**Comment by ericclemmons** [comment]
This is fixed in #5.
