### ISSUE TITLE
Transitive dependencies with npm3

### ISSUE THREAD

**Issue by insin** [ericclemmons/npm-install-loader#14]
Does something special need to be done to ensure an install isn't skipped if npm3 is being used and the user tries to import a module which is in their transitive dependencies?

e.g. if you're using `react-router` and you want to use `qs` in your own app, it will be resolved from the version of `node_modules` npm3 creates, so nothing will be installed or added to package.json

**Comment by ericclemmons** [comment]
Sure.  It'll be a bit of magic, but we can double-check `package.json` in
`process.cwd()`...

On Tue, Jan 19, 2016 at 9:18 AM Jonny Buchanan <notifications@github.com>
wrote:

> Does something special need to be done to ensure an install isn't skipped
> if npm3 is being used and the user tries to import a module which is in
> their transitive dependencies?
>
> e.g. if you're using react-router and you want to use qs in your own app,
> it will be resolved from the version of node_modules npm3 creates, so
> nothing will be installed or added to package.json
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ericclemmons/npm-install-loader/issues/14>.
>
-- 
- Eric Clemmons

**Comment by ericclemmons** [comment]
Fixed in #5.
