### ISSUE TITLE
add option to pause build and prompt instead of auto install

### ISSUE THREAD

**Issue by tikotzky** [ericclemmons/npm-install-loader#6]
For security reasons (though it may just be security theater) it might make sense to show a prompt instead of auto installing. This is to prevent a typod package for being auto installed. 

As per this conversation on Twitter: https://twitter.com/tikotzky/status/682050451467038720

**Comment by ericclemmons** [comment]
Based on #5, this may end up there (https://github.com/renke/auto-install-webpack-plugin).

Moar suggestions!

 - Timer (e.g. 5...4...3....2...1), kinda like Gmail's "undo" that a rebuild will cancel, or, if the terminal is open, a keypress will cancel it.

But, what I'm wondering is if introducing a keypress action would be no different than what we have today with:

1. Start the build & watcher in Terminal A.
2. Open Terminal B & run `npm install whatevs`.
3. Add `import whatevs from "whatevs"` in your editor & "save".
4. Terminal A picks up changes & rebuilds.

These projects would only improve the developer experience by cutting out 1 tab/window & a few keystrokes.

What sold me on this was that I would _keep coding **after** I wrote the `import`_ through the implementation a ways before ever saving. (I mean, who saves right after putting in `require` #amirite!?)

Anyway, still digging the suggestion, just wanted to think through the goals again & align any work with them.

**Comment by ericclemmons** [comment]
Just did some more research on this and I don't think this will work with regards to #5, as prompting is inherently **asynchronous**, and the script currently runs **synchronously**.

Going to close until I experiment with #5 some more and determine if there's a way around this (possibly using generators, since they do `while` loops).
